apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-csux
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-csux@sha256:b31dd04b44b7bb92cb753c0c0a6e4267220c3e20e495d8fe93aa895050bc5904
        name: my-nodejs
        resources: {}
status: {}
